# LEC-6

In [91]:
import torch
from sklearn.datasets import make_classification

In [92]:
# Step-1: Create a synthetic classification dataset using sklearn
x, y = make_classification(
    n_samples=10, # Number of Samples
    n_features=2, # Number of Features
    n_informative=2, # Number of Informative Features
    n_redundant=0, # Number of Redundant Features
    n_classes=2, # Number of Classes
    random_state=42 # Random State
)
x, y

(array([[ 1.06833894, -0.97007347],
        [-1.14021544, -0.83879234],
        [-2.8953973 ,  1.97686236],
        [-0.72063436, -0.96059253],
        [-1.96287438, -0.99225135],
        [-0.9382051 , -0.54304815],
        [ 1.72725924, -1.18582677],
        [ 1.77736657,  1.51157598],
        [ 1.89969252,  0.83444483],
        [-0.58723065, -1.97171753]]),
 array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0]))

In [93]:
x.shape, y.shape

((10, 2), (10,))

In [94]:
# Convert the Data to PyTorch Tensors
x = torch.tensor(x, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)
x, y

(tensor([[ 1.0683, -0.9701],
         [-1.1402, -0.8388],
         [-2.8954,  1.9769],
         [-0.7206, -0.9606],
         [-1.9629, -0.9923],
         [-0.9382, -0.5430],
         [ 1.7273, -1.1858],
         [ 1.7774,  1.5116],
         [ 1.8997,  0.8344],
         [-0.5872, -1.9717]]),
 tensor([1., 0., 0., 0., 0., 1., 1., 1., 1., 0.]))

## Using Dataset and DataLoader

In [95]:
from torch.utils.data import Dataset, DataLoader

In [96]:
class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features) # returns self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [97]:
# Dataset obj
dataset = CustomDataset(x, y)

In [98]:
len(dataset) # As we have 10 rows in data

10

In [99]:
dataset[0]  # 0 th element

(tensor([ 1.0683, -0.9701]), tensor(1.))

In [100]:
# Dataloader obj
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [101]:
for batch_features, batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[ 1.8997,  0.8344],
        [-1.1402, -0.8388]])
tensor([1., 0.])
--------------------------------------------------
tensor([[ 1.7774,  1.5116],
        [-0.9382, -0.5430]])
tensor([1., 1.])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.7206, -0.9606]])
tensor([0., 0.])
--------------------------------------------------
tensor([[-0.5872, -1.9717],
        [-2.8954,  1.9769]])
tensor([0., 0.])
--------------------------------------------------
tensor([[ 1.0683, -0.9701],
        [ 1.7273, -1.1858]])
tensor([1., 1.])
--------------------------------------------------


## Using Dataset & DataLoader in LEC-4 EX

In [102]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [103]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

### Data PreProcessing

In [104]:
# as columns 'id' and 'Unnamed: 32' not needed, we drop it
df.drop(columns=['id', 'Unnamed: 32'], axis=1, inplace=True)
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [105]:
# Train Test Split
x = df.drop(columns=['diagnosis'], axis=1)
y = df['diagnosis']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [106]:
# Standard Scaller
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)
x_train, x_test

(array([[ 1.42751534, -0.17285254,  1.36250954, ...,  1.41754619,
          1.02385676, -0.05176164],
        [ 0.57905357, -0.12746216,  0.67170755, ...,  0.87285694,
         -0.23891692,  1.24726594],
        [-0.37796559, -1.40974032, -0.44143507, ..., -0.94085205,
         -0.99789823, -0.81861055],
        ...,
        [ 0.35622523, -1.68889114,  0.4111056 , ...,  1.01699476,
          0.49536869,  0.95253794],
        [-0.61793458, -1.06704297, -0.60069181, ..., -0.76151425,
         -0.27678366, -0.04786901],
        [-0.41224688,  0.71225981, -0.44846718, ..., -0.33926629,
         -0.14178048, -0.1779942 ]]),
 array([[ 0.13339689,  0.1811924 ,  0.09011018, ...,  0.68623639,
          0.18749558, -0.09513671],
        [-1.39411997,  0.59197531, -1.38787516, ..., -1.36598276,
         -0.79045431, -0.55279925],
        [-0.10371532, -0.94221943, -0.1477408 , ..., -0.23882499,
          0.06566343, -0.82027882],
        ...,
        [-0.40081978, -1.42335743, -0.4662543 , ..., -

In [107]:
y_train

56     M
283    M
287    B
268    B
114    B
      ..
5      M
192    B
172    M
48     B
135    M
Name: diagnosis, Length: 455, dtype: object

In [108]:
# Label Encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)
y_train, y_test

(array([1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
        1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
        0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
        0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
        0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
        1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
        0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
        0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
        0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 

In [109]:
# NumPy Array to PyTorch Tensor
x_train_tensor  = torch.from_numpy(x_train.astype(np.float32))
x_test_tensor  = torch.from_numpy(x_test.astype(np.float32))
y_train_tensor  = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor  = torch.from_numpy(y_test.astype(np.float32))
x_train_tensor.shape, y_train_tensor.shape

(torch.Size([455, 30]), torch.Size([455]))

### DataSet and DataLoader

In [110]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [111]:
# Dataset obj
train_dataset = CustomDataset(x_train_tensor, y_train_tensor)
test_dataset = CustomDataset(x_test_tensor, y_test_tensor)
train_dataset[10]

(tensor([ 1.3132,  0.1471,  1.1722,  1.2577, -0.5055, -0.8669, -0.1253,  0.2166,
         -0.9748, -1.8527, -0.2935, -0.7226, -0.2627, -0.1027,  0.1971, -0.8372,
         -0.1866,  0.4220, -0.1628, -0.8244,  0.7509, -0.2362,  0.6322,  0.6147,
         -0.3497, -0.8893, -0.2522,  0.2083, -0.5731, -1.4737]),
 tensor(1.))

In [112]:
# Dataloader obj
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

### Defining Model

In [113]:
import torch.nn as nn

class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [114]:
# important Parameters
learning_rate = 0.1
epochs = 25

In [115]:
# Create Model
model = MySimpleNN(x_train_tensor.shape[1])

# Define Optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# Define Loss Function
loss_function = nn.BCELoss()

### Training Pipeline

In [116]:
# Define Loop
for epoch in range(epochs):
  for batch_features, batch_labels in train_loader:

    # Forward Pass
    y_pred = model(batch_features)

    # Loss
    loss = loss_function(y_pred, batch_labels.view(-1, 1))

    # Clear Gradients
    optimizer.zero_grad()

    # Backward Pass
    loss.backward()

    # Update Weights
    optimizer.step()

    # Print Loss in each epoch
    print(f"Epoch: {epoch+1}/{epochs}, Loss: {loss.item()}")

Epoch: 1/25, Loss: 0.5933165550231934
Epoch: 1/25, Loss: 0.43136662244796753
Epoch: 1/25, Loss: 0.3986583352088928
Epoch: 1/25, Loss: 0.3415001630783081
Epoch: 1/25, Loss: 0.33297795057296753
Epoch: 1/25, Loss: 0.2930663228034973
Epoch: 1/25, Loss: 0.2834784686565399
Epoch: 1/25, Loss: 0.2508673071861267
Epoch: 1/25, Loss: 0.2537975609302521
Epoch: 1/25, Loss: 0.2344931662082672
Epoch: 1/25, Loss: 0.2144826352596283
Epoch: 1/25, Loss: 0.25098204612731934
Epoch: 1/25, Loss: 0.1743616908788681
Epoch: 1/25, Loss: 0.2074715495109558
Epoch: 1/25, Loss: 0.23854544758796692
Epoch: 2/25, Loss: 0.1429360955953598
Epoch: 2/25, Loss: 0.16559180617332458
Epoch: 2/25, Loss: 0.1475832462310791
Epoch: 2/25, Loss: 0.19125394523143768
Epoch: 2/25, Loss: 0.08877535164356232
Epoch: 2/25, Loss: 0.14875736832618713
Epoch: 2/25, Loss: 0.16398225724697113
Epoch: 2/25, Loss: 0.20752786099910736
Epoch: 2/25, Loss: 0.1984027922153473
Epoch: 2/25, Loss: 0.22099310159683228
Epoch: 2/25, Loss: 0.22083780169487
Epo

### Evaluation

In [117]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.9453
