# LEC-6

In [1]:
import torch
from sklearn.datasets import make_classification

In [3]:
# Step-1: Create a synthetic classification dataset using sklearn
x, y = make_classification(
    n_samples=10, # Number of Samples
    n_features=2, # Number of Features
    n_informative=2, # Number of Informative Features
    n_redundant=0, # Number of Redundant Features
    n_classes=2, # Number of Classes
    random_state=42 # Random State
)
x, y

(array([[ 1.06833894, -0.97007347],
        [-1.14021544, -0.83879234],
        [-2.8953973 ,  1.97686236],
        [-0.72063436, -0.96059253],
        [-1.96287438, -0.99225135],
        [-0.9382051 , -0.54304815],
        [ 1.72725924, -1.18582677],
        [ 1.77736657,  1.51157598],
        [ 1.89969252,  0.83444483],
        [-0.58723065, -1.97171753]]),
 array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0]))

In [4]:
x.shape, y.shape

((10, 2), (10,))

In [5]:
# Convert the Data to PyTorch Tensors
x = torch.tensor(x, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)
x, y

(tensor([[ 1.0683, -0.9701],
         [-1.1402, -0.8388],
         [-2.8954,  1.9769],
         [-0.7206, -0.9606],
         [-1.9629, -0.9923],
         [-0.9382, -0.5430],
         [ 1.7273, -1.1858],
         [ 1.7774,  1.5116],
         [ 1.8997,  0.8344],
         [-0.5872, -1.9717]]),
 tensor([1., 0., 0., 0., 0., 1., 1., 1., 1., 0.]))

## Using Dataset and DataLoader

In [6]:
from torch.utils.data import Dataset, DataLoader

In [7]:
class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features) # returns self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [14]:
# Dataset obj
dataset = CustomDataset(x, y)

In [15]:
len(dataset) # As we have 10 rows in data

10

In [16]:
dataset[0]  # 0 th element

(tensor([ 1.0683, -0.9701]), tensor(1.))

In [17]:
# Dataloader obj
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [18]:
for batch_features, batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[-1.9629, -0.9923],
        [-2.8954,  1.9769]])
tensor([0., 0.])
--------------------------------------------------
tensor([[-0.7206, -0.9606],
        [ 1.8997,  0.8344]])
tensor([0., 1.])
--------------------------------------------------
tensor([[ 1.7774,  1.5116],
        [ 1.0683, -0.9701]])
tensor([1., 1.])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [-1.1402, -0.8388]])
tensor([1., 0.])
--------------------------------------------------
tensor([[-0.9382, -0.5430],
        [-0.5872, -1.9717]])
tensor([1., 0.])
--------------------------------------------------
