# LEC-5

# Model with single Neuron

In [16]:
# Create Model Class
import torch
import torch.nn as nn

# NN Architecture
class Model(nn.Module):
  def __init__(self, num_input_features):
    super(Model, self).__init__()
    self.linear = nn.Linear(num_input_features, 1) # nn.Linear(input, output)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features) # z = wx+b
    out = self.sigmoid(out) # y_pred = sigmoid(z)
    return out

In [17]:
# Create Dataset
features = torch.rand(10,5) # 10 rows, 5 columns, so 5 features

# Create Model
model = Model(features.shape[1])

# Call Model for Forward pass
# use model.forward(features) or model(features)
model(features)

tensor([[0.2821],
        [0.3402],
        [0.2737],
        [0.3205],
        [0.2995],
        [0.3005],
        [0.2903],
        [0.3443],
        [0.2847],
        [0.3385]], grad_fn=<SigmoidBackward0>)

In [18]:
# Show Model Weights
model.linear.weight

Parameter containing:
tensor([[-0.4437, -0.0467, -0.1107, -0.4119, -0.1285]], requires_grad=True)

In [19]:
# Show Model Bias
model.linear.bias

Parameter containing:
tensor([-0.2321], requires_grad=True)

In [20]:
!pip install torchinfo

In [21]:
# To get a summary of the Model
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Model with Hidden Layer

In [22]:
# Create Model Class
import torch
import torch.nn as nn

# NN Architecture
class Model(nn.Module):
  def __init__(self, num_input_features):
    super(Model, self).__init__()
    self.linear1 = nn.Linear(num_input_features, 3) # 5 i/p, 3 o/p
    self.relu = nn.ReLU() # Activation function of Layer1
    self.linear2 = nn.Linear(3, 1)  # 3 i/p, 1 o/p
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

In [23]:
# Create Dataset
features = torch.rand(10,5)

# Create Model
model = Model(features.shape[1])

# Call Model for Forward pass
# use model.forward(features) or model(features)
model(features)

tensor([[0.4006],
        [0.4186],
        [0.4008],
        [0.4442],
        [0.4001],
        [0.4161],
        [0.4000],
        [0.3964],
        [0.4022],
        [0.4169]], grad_fn=<SigmoidBackward0>)

In [24]:
model.linear1.weight

Parameter containing:
tensor([[-0.2816,  0.1359,  0.2689, -0.2396,  0.4192],
        [-0.2192,  0.1655,  0.4149,  0.4256, -0.4232],
        [-0.1893,  0.1922,  0.2813,  0.3570,  0.2047]], requires_grad=True)

In [25]:
model.linear2.weight

Parameter containing:
tensor([[-0.3920, -0.3208,  0.3178]], requires_grad=True)

In [26]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Using Sequential Container

In [27]:
# Create Model Class
import torch
import torch.nn as nn

# NN Architecture
class Model(nn.Module):
  def __init__(self, num_input_features):
    super(Model, self).__init__()
    self.network = nn.Sequential(
        nn.Linear(num_input_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out

In [28]:
# Create Dataset
features = torch.rand(10,5)

# Create Model
model = Model(features.shape[1])

# Call Model for Forward pass
# use model.forward(features) or model(features)
model(features)

tensor([[0.3276],
        [0.3326],
        [0.3375],
        [0.3251],
        [0.3299],
        [0.3252],
        [0.3312],
        [0.3223],
        [0.3338],
        [0.3416]], grad_fn=<SigmoidBackward0>)