# LEC-5

# Model with single Neuron

In [94]:
# Create Model Class
import torch
import torch.nn as nn

# NN Architecture
class Model(nn.Module):
  def __init__(self, num_input_features):
    super(Model, self).__init__()
    self.linear = nn.Linear(num_input_features, 1) # nn.Linear(input, output)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features) # z = wx+b
    out = self.sigmoid(out) # y_pred = sigmoid(z)
    return out

In [95]:
# Create Dataset
features = torch.rand(10,5) # 10 rows, 5 columns, so 5 features

# Create Model
model = Model(features.shape[1])

# Call Model for Forward pass
# use model.forward(features) or model(features)
model(features)

tensor([[0.5654],
        [0.5331],
        [0.4803],
        [0.5682],
        [0.4921],
        [0.5473],
        [0.5451],
        [0.5543],
        [0.4450],
        [0.5439]], grad_fn=<SigmoidBackward0>)

In [96]:
# Show Model Weights
model.linear.weight

Parameter containing:
tensor([[ 0.0008,  0.1209,  0.2488, -0.4412, -0.1776]], requires_grad=True)

In [97]:
# Show Model Bias
model.linear.bias

Parameter containing:
tensor([0.1770], requires_grad=True)

In [98]:
!pip install torchinfo

In [99]:
# To get a summary of the Model
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Model with Hidden Layer

In [100]:
# Create Model Class
import torch
import torch.nn as nn

# NN Architecture
class Model(nn.Module):
  def __init__(self, num_input_features):
    super(Model, self).__init__()
    self.linear1 = nn.Linear(num_input_features, 3) # 5 i/p, 3 o/p
    self.relu = nn.ReLU() # Activation function of Layer1
    self.linear2 = nn.Linear(3, 1)  # 3 i/p, 1 o/p
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

In [101]:
# Create Dataset
features = torch.rand(10,5)

# Create Model
model = Model(features.shape[1])

# Call Model for Forward pass
# use model.forward(features) or model(features)
model(features)

tensor([[0.4011],
        [0.4378],
        [0.4141],
        [0.4309],
        [0.4219],
        [0.4043],
        [0.4115],
        [0.4489],
        [0.4258],
        [0.4132]], grad_fn=<SigmoidBackward0>)

In [102]:
model.linear1.weight

Parameter containing:
tensor([[-0.3764, -0.2074,  0.1010,  0.1053,  0.3559],
        [ 0.2282,  0.1113,  0.1349, -0.2280,  0.1594],
        [ 0.4105,  0.1315,  0.2936,  0.2040, -0.1702]], requires_grad=True)

In [103]:
model.linear2.weight

Parameter containing:
tensor([[0.0177, 0.3224, 0.1124]], requires_grad=True)

In [104]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Using Sequential Container

In [105]:
# Create Model Class
import torch
import torch.nn as nn

# NN Architecture
class Model(nn.Module):
  def __init__(self, num_input_features):
    super(Model, self).__init__()
    self.network = nn.Sequential(
        nn.Linear(num_input_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out

In [106]:
# Create Dataset
features = torch.rand(10,5)

# Create Model
model = Model(features.shape[1])

# Call Model for Forward pass
# use model.forward(features) or model(features)
model(features)

tensor([[0.5183],
        [0.5210],
        [0.4675],
        [0.5116],
        [0.4879],
        [0.5266],
        [0.4916],
        [0.5072],
        [0.4787],
        [0.4553]], grad_fn=<SigmoidBackward0>)

# Using NN module in Lec-4 Example

In [107]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [108]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

## Data Preprocessing

In [109]:
# as columns 'id' and 'Unnamed: 32' not needed, we drop it
df.drop(columns=['id', 'Unnamed: 32'], axis=1, inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [110]:
# Train Test Split
x = df.drop(columns=['diagnosis'], axis=1)
y = df['diagnosis']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [111]:
# Standard Scaller
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)
x_train, x_test

(array([[-0.36316993, -0.70542054, -0.40031241, ..., -0.84857574,
          1.07837422, -0.75306942],
        [-0.09596279,  1.03780579, -0.0219701 , ...,  1.30781973,
          2.37135661,  1.38543122],
        [-0.59626553, -1.070712  , -0.57918012, ..., -0.73316726,
         -0.25989378, -0.05543848],
        ...,
        [-1.30209036, -0.77477968, -1.31402143, ..., -0.6318843 ,
         -0.24427806, -0.12469482],
        [-1.26911586,  0.01822646, -1.27940187, ..., -1.13920075,
         -0.56440051, -0.26996422],
        [-1.10509616, -1.62789707, -1.08569721, ..., -0.71092708,
          0.03680507, -0.38145004]]),
 array([[-1.01697465,  0.22167993, -0.90435667, ...,  0.48433212,
         -0.49412972,  2.02731925],
        [-0.74123962, -1.11463945, -0.71889476, ..., -0.67756682,
         -0.91263127, -0.14946945],
        [ 0.39296944,  3.30584958,  0.47836492, ...,  1.30932244,
          0.93470951,  2.04984164],
        ...,
        [ 0.20251328, -0.53664664,  0.11527171, ..., -

In [112]:
y_train

268    B
203    M
48     B
441    M
261    M
      ..
266    B
264    M
234    B
548    B
390    B
Name: diagnosis, Length: 455, dtype: object

In [113]:
# Label Encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)
y_train, y_test

(array([0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
        0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
        0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
        0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
        1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
        1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
        1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
        1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
        1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 

In [114]:
# NumPy Array to PyTorch Tensor
x_train_tensor  = torch.from_numpy(x_train)
x_test_tensor  = torch.from_numpy(x_test)
y_train_tensor  = torch.from_numpy(y_train)
y_test_tensor  = torch.from_numpy(y_test)
x_train_tensor.shape, y_train_tensor.shape

(torch.Size([455, 30]), torch.Size([455]))

## Defining Model

In [115]:
import torch.nn as nn

class MySimpleNN(nn.Module):
  def __init__(self, num_input_features):
    super().__init__()
    self.linear = nn.Linear(num_input_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out


In [116]:
learning_rate = 0.1
epochs = 25
x_train_tensor = x_train_tensor.float()
y_train_tensor = y_train_tensor.float().view(-1, 1)
x_test_tensor = x_test_tensor.float()
y_test_tensor = y_test_tensor.float().view(-1, 1)

In [117]:
# Built in Loss Function
loss_function = nn.BCELoss()

## Training Pipeline

In [118]:
# create Model
model = MySimpleNN(x_train_tensor.shape[1])

# Defining Optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# Define loop
for epoch in range(epochs):

  # Forward Pass
  y_pred = model(x_train_tensor)

  # Calculate Loss
  loss = loss_function(y_pred, y_train_tensor)

  # Zero Gradients
  optimizer.zero_grad()

  # Backward Pass
  loss.backward()

  # Update Weights
  optimizer.step()

  # Print Loss in epochs
  print(f'Epoch: {epoch}, Loss: {loss.item()}')

Epoch: 0, Loss: 0.682421088218689
Epoch: 1, Loss: 0.5187644958496094
Epoch: 2, Loss: 0.43129870295524597
Epoch: 3, Loss: 0.3765679895877838
Epoch: 4, Loss: 0.338614284992218
Epoch: 5, Loss: 0.31045302748680115
Epoch: 6, Loss: 0.28854402899742126
Epoch: 7, Loss: 0.2708945572376251
Epoch: 8, Loss: 0.25629276037216187
Epoch: 9, Loss: 0.2439567744731903
Epoch: 10, Loss: 0.233357772231102
Epoch: 11, Loss: 0.22412431240081787
Epoch: 12, Loss: 0.2159872055053711
Epoch: 13, Loss: 0.20874600112438202
Epoch: 14, Loss: 0.20224812626838684
Epoch: 15, Loss: 0.1963750422000885
Epoch: 16, Loss: 0.1910332888364792
Epoch: 17, Loss: 0.1861477643251419
Epoch: 18, Loss: 0.1816575676202774
Epoch: 19, Loss: 0.17751258611679077
Epoch: 20, Loss: 0.17367123067378998
Epoch: 21, Loss: 0.17009852826595306
Epoch: 22, Loss: 0.1667650192975998
Epoch: 23, Loss: 0.16364546120166779
Epoch: 24, Loss: 0.16071826219558716


In [119]:
model.linear.weight

Parameter containing:
tensor([[ 0.3330,  0.1336,  0.1397,  0.2899,  0.1788,  0.3120,  0.1643,  0.2146,
          0.0046, -0.1571,  0.2916,  0.1100,  0.0795,  0.1924,  0.0614, -0.0357,
         -0.0247, -0.0461, -0.0289, -0.1239,  0.3438,  0.1260,  0.0831,  0.2395,
          0.2261,  0.1898,  0.3155,  0.4092,  0.0253,  0.0619]],
       requires_grad=True)

In [120]:
model.linear.bias

Parameter containing:
tensor([-0.0969], requires_grad=True)

In [121]:
# Evaluation
with torch.no_grad():
  y_pred = model(x_test_tensor)
  y_pred = torch.where(y_pred > 0.5, 1, 0)
  accuracy = (y_pred == y_test_tensor).sum().item() / len(y_test_tensor)
  print(f'Accuracy: {accuracy}')

Accuracy: 0.956140350877193
