# LEC-4
Code Flow
1. Load the dataset
2. Basic Preprocessing
3. Training Process
  *  a. Create the model
  *  b. Forward pass
  *  c. Loss calculation
  *  d. Backprop
  *  e. Parameters update
4. Model evaluation

In [20]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

# 1. Load the dataset

In [21]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [22]:
df.shape

(569, 33)

# 2. Data Preprocessing

In [23]:
# as columns 'id' and 'Unnamed: 32' not needed, we drop it
df.drop(columns=['id', 'Unnamed: 32'], axis=1, inplace=True)
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

## A. Train Test Split

In [24]:
x = df.drop(columns=['diagnosis'], axis=1)
y = df['diagnosis']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

## B. Scaling

In [25]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)
x_train, x_test

(array([[ 0.09345681,  1.27961569,  0.15272009, ...,  0.07523943,
          0.43856301,  1.06057587],
        [ 0.84443084, -0.70683785,  0.97650522, ...,  2.11573912,
          1.85759674,  1.2702611 ],
        [ 2.95109582,  0.49567186,  2.99618643, ...,  2.00195661,
          0.39013183,  0.7349813 ],
        ...,
        [-0.53094856, -0.35070998, -0.56294068, ..., -0.50717531,
          0.31909942, -0.16142307],
        [ 0.11033263, -0.02695736,  0.08906953, ..., -0.29736036,
         -0.71732795, -0.55108812],
        [ 1.56165323,  0.41473371,  1.54772819, ...,  1.9336871 ,
          1.12628584,  0.20319625]]),
 array([[-1.87806869e-01, -1.24796722e+00, -1.93685836e-01, ...,
          2.72462449e-01,  5.03137925e-01,  5.34032954e-01],
        [-5.30948561e-01,  6.89923430e-01, -5.66612832e-01, ...,
         -7.91783299e-01,  2.98112574e-01, -1.20068478e-01],
        [-3.20000799e-01,  1.31199095e+00, -3.85861564e-01, ...,
         -8.54591245e-01, -9.83699467e-01, -1.23373004e+

In [26]:
y_train

541    B
25     M
521    M
394    B
319    B
      ..
212    M
410    B
155    B
448    B
2      M
Name: diagnosis, Length: 455, dtype: object

## C. Label Encoding

In [27]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)
y_train, y_test

(array([0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
        0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
        1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
        0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
        1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
        1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 

## D. NumPy Array to PyTorch tensors

In [28]:
x_train_tensor  = torch.from_numpy(x_train)
x_test_tensor  = torch.from_numpy(x_test)
y_train_tensor  = torch.from_numpy(y_train)
y_test_tensor  = torch.from_numpy(y_test)
x_train_tensor.shape, y_train_tensor.shape

(torch.Size([455, 30]), torch.Size([455]))

# 3. Training Process

## A. Defining the model

In [46]:
class MySimpleNN():
  def __init__(self, x):
    self.weights = torch.rand(x.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, x):
    z = torch.matmul(x, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
    return loss


## B. important Parameters

In [47]:
learning_rate = 0.1
epoches = 25

## C. Training Pipeline

In [51]:
# Create Model
model = MySimpleNN(x_train_tensor)

# Define loop
for epoch in range(epoches):
  # Forward Pass
  y_pred = model.forward(x_train_tensor)

  # Loss Calculation
  loss = model.loss_function(y_pred, y_train_tensor)

  # Backprop
  loss.backward()

  # Parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # Zero Gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # Print Loss in each epoches
  print(f'Epoch: {epoch}, Loss: {loss}')

Epoch: 0, Loss: 3.8569387618649125
Epoch: 1, Loss: 3.7251379956918176
Epoch: 2, Loss: 3.592942293331391
Epoch: 3, Loss: 3.453393436757455
Epoch: 4, Loss: 3.3084070663403056
Epoch: 5, Loss: 3.1518423731370433
Epoch: 6, Loss: 2.990592469618694
Epoch: 7, Loss: 2.8266829033793117
Epoch: 8, Loss: 2.657434682348252
Epoch: 9, Loss: 2.4821632594265877
Epoch: 10, Loss: 2.308108737892481
Epoch: 11, Loss: 2.1280942492535373
Epoch: 12, Loss: 1.9474239407257745
Epoch: 13, Loss: 1.7680545648477237
Epoch: 14, Loss: 1.5942124721520707
Epoch: 15, Loss: 1.4321038017041585
Epoch: 16, Loss: 1.2843656083910096
Epoch: 17, Loss: 1.1537845291841167
Epoch: 18, Loss: 1.0428826794066681
Epoch: 19, Loss: 0.9533068012518184
Epoch: 20, Loss: 0.8851725562110465
Epoch: 21, Loss: 0.8366497982381218
Epoch: 22, Loss: 0.804058715723721
Epoch: 23, Loss: 0.7827952016825368
Epoch: 24, Loss: 0.7687602109133401


# 4. Evaluation

In [52]:
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.5).float() # Changing y_pred to 0 or 1
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy}')

Accuracy: 0.5554016828536987
