In [27]:
# Importing PyTorch
import torch
print(torch.__version__)

2.6.0+cu124


In [28]:
# To check if GPU is available
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available. Using CPU")

GPU is available
Using GPU: Tesla T4


# Creating a **Tensor**


In [29]:
# Using 'empty' func
a = torch.empty(2,3)

In [30]:
# check type
type(a)

torch.Tensor

In [31]:
# Using 'zeros' func
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [32]:
# Using 'ones'
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [33]:
# Using 'rand'
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [34]:
# Use of 'seed'
torch.rand(2,3) # As rand gives random value every time it is problematic

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [35]:
# Using 'manual_seed'
torch.manual_seed(100)  # Gives same o/p for rand func
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [36]:
torch.manual_seed(100)  # seed value must be same to get same rand o/p
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [37]:
# Using Tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [38]:
# Other Ways

# arange -> to get data in range and last alue is step or jump
print("using arange -> ", torch.arange(1,10, 2))

# linspace -> to get evenly spaced values in range
print("using linspace -> ", torch.linspace(1,10, 10))

# using eye -> to get identity matrix
print("using eye -> ", torch.eye(5))

# using full -> to get every item as same value in a shape
print("using full -> ", torch.full((3, 3), 5))

using arange ->  tensor([1, 3, 5, 7, 9])
using linspace ->  tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
using eye ->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full ->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor **Shapes**

In [39]:
x = torch.tensor([[1, 2, 3],[4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [40]:
x.shape

torch.Size([2, 3])

In [41]:
torch.empty_like(x) # To get a new tensor with same shape as x

tensor([[3616445622929465956, 6068090518685887797, 3688512086410408753],
        [6498752769165702702, 7309453675965983778, 8315168162784306286]])

In [42]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [43]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [56]:
torch.rand_like(x, dtype=torch.float64)

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

# Tensor Data Types

In [45]:
# find data type
x.dtype

torch.int64

In [50]:
# assign data type
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [51]:
torch.tensor([1, 2, 3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [57]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical Operations

## 1. Scalar operations

In [58]:
x = torch.rand(2,2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [63]:
# addition
print("addition -> ", x + 2)

#subtraction
print("subtraction -> ", x - 2)

#multiplication
print("multiplication -> ", x * 2)

#division
print("division -> ", x / 2)

#power
print("power -> ", x ** 2)

# int division
print("int division -> ", x // 2)

#modulus
print("modulus -> ", x % 2)

addition ->  tensor([[2.2239, 2.3023],
        [2.1784, 2.8238]])
subtraction ->  tensor([[-1.7761, -1.6977],
        [-1.8216, -1.1762]])
multiplication ->  tensor([[0.4478, 0.6047],
        [0.3568, 1.6477]])
division ->  tensor([[0.1119, 0.1512],
        [0.0892, 0.4119]])
power ->  tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])
int division ->  tensor([[0., 0.],
        [0., 0.]])
modulus ->  tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])


## 2. Element Wise Operations

In [64]:
a = torch.rand(2,3)
b = torch.rand(2,3)
a, b

(tensor([[0.5557, 0.9770, 0.4440],
         [0.9478, 0.7445, 0.4892]]),
 tensor([[0.2426, 0.7003, 0.5277],
         [0.2472, 0.7909, 0.4235]]))

In [65]:
# addition
print("addition -> ", a + b)

#subtraction
print("subtraction -> ", a - b)

#multiplication
print("multiplication -> ", a * b)

#division
print("division -> ", a / b)

# power
print("power -> ", a ** b)

# int division
print("int division -> ", a // b)

#modulus
print("modulus -> ", a % b)

addition ->  tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])
subtraction ->  tensor([[ 0.3132,  0.2767, -0.0837],
        [ 0.7007, -0.0464,  0.0657]])
multiplication ->  tensor([[0.1348, 0.6842, 0.2343],
        [0.2343, 0.5888, 0.2072]])
division ->  tensor([[2.2912, 1.3951, 0.8415],
        [3.8346, 0.9413, 1.1552]])
power ->  tensor([[0.8672, 0.9839, 0.6515],
        [0.9868, 0.7919, 0.7388]])
int division ->  tensor([[2., 1., 0.],
        [3., 0., 1.]])
modulus ->  tensor([[0.0706, 0.2767, 0.4440],
        [0.2063, 0.7445, 0.0657]])


In [67]:
c = torch.tensor([1, -2, 3, -4])
c

tensor([ 1, -2,  3, -4])

In [68]:
# absolute
torch.abs(c)

tensor([1, 2, 3, 4])

In [69]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [70]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [71]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [72]:
# ceil (ceiling value)
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [73]:
# floor (floor value)
torch.floor(d)

tensor([1., 2., 3., 4.])

In [74]:
# clamp (values will become within 2 and 3)
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## 3. Reduction Operation

In [78]:
e = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 7., 5.],
        [9., 9., 7.]])

In [79]:
# sum
print("sum -> ", torch.sum(e))

# sum along columns
print("sum along columns -> ", torch.sum(e, dim=0))

# sum along rows
print("sum along rows -> ", torch.sum(e, dim=1))

sum ->  tensor(42.)
sum along columns ->  tensor([14., 16., 12.])
sum along rows ->  tensor([17., 25.])


In [80]:
# mean
print("mean -> ", torch.mean(e))

# mean along columns
print("mean along columns -> ", torch.mean(e, dim=0))

# mean along rows
print("mean along rows -> ", torch.mean(e, dim=1))

mean ->  tensor(7.)
mean along columns ->  tensor([7., 8., 6.])
mean along rows ->  tensor([5.6667, 8.3333])


In [81]:
# median
print("median -> ", torch.median(e))

# median along columns
print("median along columns -> ", torch.median(e, dim=0))

# median along rows
print("median along rows -> ", torch.median(e, dim=1))

median ->  tensor(7.)
median along columns ->  torch.return_types.median(
values=tensor([5., 7., 5.]),
indices=tensor([0, 0, 0]))
median along rows ->  torch.return_types.median(
values=tensor([5., 9.]),
indices=tensor([2, 0]))


In [82]:
# max and min
print("max -> ", torch.max(e))
print("min -> ", torch.min(e))

max ->  tensor(9.)
min ->  tensor(5.)


In [83]:
# product
print("product -> ", torch.prod(e))

# product along columns
print("product along columns -> ", torch.prod(e, dim=0))

# product along rows
print("product along rows -> ", torch.prod(e, dim=1))

product ->  tensor(99225.)
product along columns ->  tensor([45., 63., 35.])
product along rows ->  tensor([175., 567.])


In [84]:
# standard deviation
print("standard deviation -> ", torch.std(e))

# standard deviation along columns
print("standard deviation along columns -> ", torch.std(e, dim=0))

# standard deviation along rows
print("standard deviation along rows -> ", torch.std(e, dim=1))

standard deviation ->  tensor(1.7889)
standard deviation along columns ->  tensor([2.8284, 1.4142, 1.4142])
standard deviation along rows ->  tensor([1.1547, 1.1547])


In [85]:
# varience
print("varience -> ", torch.var(e))

# varience along columns
print("varience along columns -> ", torch.var(e, dim=0))

# varience along rows
print("varience along rows -> ", torch.var(e, dim=1))

varience ->  tensor(3.2000)
varience along columns ->  tensor([8., 2., 2.])
varience along rows ->  tensor([1.3333, 1.3333])


In [87]:
# argmax -> (to get position of max item)
print("argmax -> ", torch.argmax(e))

# argmax along columns
print("argmax along columns -> ", torch.argmax(e, dim=0))

# argmax along rows
print("argmax along rows -> ", torch.argmax(e, dim=1))

argmax ->  tensor(3)
argmax along columns ->  tensor([1, 1, 1])
argmax along rows ->  tensor([1, 0])


In [88]:
# argmin -> (to get min item position)
print("argmin -> ", torch.argmin(e))

# argmin along columns
print("argmin along columns -> ", torch.argmin(e, dim=0))

# argmin along rows
print("argmin along rows -> ", torch.argmin(e, dim=1))

argmin ->  tensor(0)
argmin along columns ->  tensor([0, 0, 0])
argmin along rows ->  tensor([0, 2])


## 4. Matrix operations

In [89]:
f = torch.randint(size=(2, 3), low=0, high=10)
g = torch.randint(size=(3, 2), low=0, high=10)
f, g

(tensor([[5, 9, 8],
         [9, 7, 9]]),
 tensor([[2, 6],
         [7, 7],
         [8, 3]]))

In [90]:
# Matrix Multiplication
torch.matmul(f, g)

tensor([[137, 117],
        [139, 130]])

In [94]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])
print(vector1, vector2)
# Dot Product
torch.dot(vector1, vector2)

tensor([1, 2]) tensor([3, 4])


tensor(11)

In [95]:
# Transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [9, 7],
        [8, 9]])

In [97]:
h = torch.randint(size=(3, 3), low=0, high=10, dtype=torch.float32)
h

tensor([[3., 8., 8.],
        [3., 3., 5.],
        [0., 6., 4.]])

In [98]:
# Determinant
torch.det(h)

tensor(-6.)

In [99]:
# Inverse
torch.inverse(h)

tensor([[ 3.0000, -2.6667, -2.6667],
        [ 2.0000, -2.0000, -1.5000],
        [-3.0000,  3.0000,  2.5000]])

## 5. Comparison Operations

In [100]:
i = torch.randint(size=(2, 3), low=0, high=10)
j = torch.randint(size=(2, 3), low=0, high=10)
i, j

(tensor([[0, 8, 4],
         [7, 2, 3]]),
 tensor([[8, 5, 6],
         [2, 9, 5]]))

In [101]:
# Greater than
print("Greater than -> ", i > j)

# Less than
print("Less than -> ", i < j)

# Equal to
print("Equal to -> ", i == j)

# Not Equal to
print("Not equal to -> ", i != j)

# Grater than Equal to
print("Grater than Equal to -> ", i >= j)

# Less than Equal to
print("Less than Equal to -> ", i <= j)

Greater than ->  tensor([[False,  True, False],
        [ True, False, False]])
Less than ->  tensor([[ True, False,  True],
        [False,  True,  True]])
Equal to ->  tensor([[False, False, False],
        [False, False, False]])
Not equal to ->  tensor([[True, True, True],
        [True, True, True]])
Grater than Equal to ->  tensor([[False,  True, False],
        [ True, False, False]])
Less than Equal to ->  tensor([[ True, False,  True],
        [False,  True,  True]])


## 6. Special Functions

In [108]:
k = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float32)
k

tensor([[5., 4., 4.],
        [1., 1., 2.]])

In [109]:
# Log
torch.log(k)

tensor([[1.6094, 1.3863, 1.3863],
        [0.0000, 0.0000, 0.6931]])

In [110]:
# Exponents
torch.exp(k)

tensor([[148.4132,  54.5981,  54.5981],
        [  2.7183,   2.7183,   7.3891]])

In [111]:
# Square root
torch.sqrt(k)

tensor([[2.2361, 2.0000, 2.0000],
        [1.0000, 1.0000, 1.4142]])

In [112]:
# Sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.9820, 0.9820],
        [0.7311, 0.7311, 0.8808]])

In [113]:
# Softmax
torch.softmax(k, dim=0)

tensor([[0.9820, 0.9526, 0.8808],
        [0.0180, 0.0474, 0.1192]])

In [115]:
# relu
torch.relu(k)

tensor([[5., 4., 4.],
        [1., 1., 2.]])

# Inplace Operations

In [124]:
m = torch.rand(size=(2, 3))
n = torch.rand(size=(2, 3))
m, n

(tensor([[0.6594, 0.0887, 0.4890],
         [0.5887, 0.7340, 0.8497]]),
 tensor([[0.9112, 0.4847, 0.9436],
         [0.3904, 0.2499, 0.3206]]))

In [125]:
m + n # Stores ans in new tensor (it does memory loss, uses memory)

tensor([[1.5705, 0.5734, 1.4325],
        [0.9792, 0.9839, 1.1703]])

In [126]:
m.add_(n)

tensor([[1.5705, 0.5734, 1.4325],
        [0.9792, 0.9839, 1.1703]])

In [128]:
m # so this is how we do inplace operations

tensor([[1.5705, 0.5734, 1.4325],
        [0.9792, 0.9839, 1.1703]])

In [130]:
m.relu_() # functions with '_' is inplace operations

tensor([[1.5705, 0.5734, 1.4325],
        [0.9792, 0.9839, 1.1703]])

# Copying a Tensor

In [145]:
a = torch.rand(2,3)
a

tensor([[0.5688, 0.0634, 0.8993],
        [0.2732, 0.3397, 0.1879]])

In [146]:
b = a # Changing values of a will change in b which is not alwas desirable
b

tensor([[0.5688, 0.0634, 0.8993],
        [0.2732, 0.3397, 0.1879]])

In [147]:
a[0][0]=0
a, b

(tensor([[0.0000, 0.0634, 0.8993],
         [0.2732, 0.3397, 0.1879]]),
 tensor([[0.0000, 0.0634, 0.8993],
         [0.2732, 0.3397, 0.1879]]))

In [148]:
# a and b are pointing to a same memory space
id(a) == id(b)

True

In [149]:
b = a.clone() # b has a new Memory location
a, b

(tensor([[0.0000, 0.0634, 0.8993],
         [0.2732, 0.3397, 0.1879]]),
 tensor([[0.0000, 0.0634, 0.8993],
         [0.2732, 0.3397, 0.1879]]))

In [150]:
a[0][0] = 10
a, b

(tensor([[10.0000,  0.0634,  0.8993],
         [ 0.2732,  0.3397,  0.1879]]),
 tensor([[0.0000, 0.0634, 0.8993],
         [0.2732, 0.3397, 0.1879]]))

In [151]:
id(a) == id(b)

False

# Tensor Operations on GPU

In [153]:
torch.cuda.is_available()

True

In [154]:
device = torch.device('cuda')
device

device(type='cuda')

In [155]:
# Creating a new Tensor on GPU
torch.rand(2,3, device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [157]:
a = torch.rand(2,3) # Tensor on CPU
a

tensor([[0.9431, 0.8519, 0.9815],
        [0.1132, 0.4783, 0.4436]])

In [159]:
# Moving an existing Tensor to GPU
b = a.to(device)
b

tensor([[0.9431, 0.8519, 0.9815],
        [0.1132, 0.4783, 0.4436]], device='cuda:0')

In [163]:
b + 5 # Operation performed on GPU

tensor([[5.9431, 5.8519, 5.9815],
        [5.1132, 5.4783, 5.4436]], device='cuda:0')